<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vetrivendans-MacBook-Air.local" failures="1" tests="4" name="SeleniumFrameworkDesign.Tests.ErrorValidationsTest" time="26.238" errors="0" timestamp="2025-03-18T23:41:44 AEDT" skipped="2">
  <testcase classname="SeleniumFrameworkDesign.Tests.ErrorValidationsTest" name="LoginErrorValidation" time="5.867">
    <failure message="expected [Incorrect email or password.----] but found [Incorrect email or password.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.----] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SeleniumFrameworkDesign.Tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="SeleniumFrameworkDesign.Tests.ErrorValidationsTest" name="LoginErrorValidation" time="5.963">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="SeleniumFrameworkDesign.Tests.ErrorValidationsTest" name="ProductErrorValidation" time="7.865"/>
  <testcase classname="SeleniumFrameworkDesign.Tests.ErrorValidationsTest" name="LoginErrorValidation" time="6.543">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
</testsuite> <!-- SeleniumFrameworkDesign.Tests.ErrorValidationsTest -->
